language: elixir
elixir:
- 1.4
otp_release:
- 18.2.1
script:
- mix test
- mix escript.build
deploy:
  provider: releases
  api_key:
    secure: FgSWG79PH6Dr+ltvr2labKGQiTcykDS55n9geppY+MP1R/kBrvWD1SeX1r8wRuSVYKnZfZt89csWR2D6lLMXcr8zeENpdDcJFf3DGF2L3UXhTvumE9GyV0Jnsgl22o71NVZD/N/foCbMcYrFRRmj2ID5MyA04MJDWLAXPQqVn9x1NQZNCN8EKK3PZd9lBvTeMtbHJBPCAGzl0otPZN5aNrj5Jmdwab19zqcqg6fyUfy+8SJLlWMv3Yrx7sJ3DS5dN7XzxCn/bxDAWe2Rjz+FAOMtPMFwTvQDDRqayEvsrWWM1CFVi8+OxlZPgbVDWOEoYNbcOeFusiXartspbBnR9Rc1fq2HOgW5geAV4h66wAKgNEV7klGa9l5WguZ/sxHMGxSOJpdtmM7m3cc2no1W9P/H2VXRQ62N79qPWjKgxJeZQo7PeD+gswI8iSNVO142WmPNSQAhl55C4Zk/aNzRDQD8ZMLergqX+u70d8pwTHlUb2OSytvm8ZiuF1F/dRkkvyv6yaYRYgC+tawJdlsHY0AqHGMxlMFFx7aLbdU1e3e9hShvDLenv50yFgc6ou3//qeAge0LiUmlNTpeunFZoMRfDddaJKmsmpcgR2E5H8zNy35gEBTKJSPGja6Bz+QrrsdL+Qtw7+5xdThDmPeTb58LtuwtuppR0u5dS0Oph7E=
  file: slap
  on:
    repo: derniercri/slap
    branch: travis
    tags: true
